# -*- coding: utf-8 -*-
"""Chapter2_Lambert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JqVhmt9kCoGQ9aLK_mP2XQc8aVORauml
"""

myList =[]
print(myList)
print(type(myList))

import math
x = 2
y = [x, math.sqrt(x)]
print(y)
print(type(y[0]), type(y[1]))

file_path = '/content/drive/MyDrive/SoftwareLab/my_list.txt'

# prompt: read from a text file containing numbers and put it in the list and display the elements
#my_list = []

file = open(file_path, 'r')
for line in file:
  #print(line)
  #print(type(line))
  line.strip()
print('After stripping:', line)
myList = line.split()
for i in range(len(myList)):
  myList[i] = int(myList[i])
print(myList)
file.close()

myList
  #print(type(line))
  #print(type(int(line.strip)))
    #myList.append(int(line.strip()))
#file.close()

#myList

myNumbers = []
myNumbers = list(range(1, 10, 2))
print(myNumbers)
myNumbers.append(10)
print(myNumbers)
myNumbers.extend([100])
print(myNumbers)
myNumbers.pop(3)
print(myNumbers)

myNumbers = tuple(['4', '5', '50', '100'])
print(myNumbers)
print(type(myNumbers))
myNumbers

phoneBook = {"one":'uno', "two":200, "three":300}
print(phoneBook)
print(type(phoneBook))
phoneBook
print(type(phoneBook["one"]))

import json
file_path = '/content/drive/MyDrive/SoftwareLab/stnds.json'

# student_dict = [
# {"ID":"001" , "FN":"Aaron", "LN":"Uy", "Grade":"1.00"},
# {"ID":"002" , "FN":"Nathan", "LN":"Galang", "Grade":"1.00"},
# {"ID":"003" , "FN":"Neil", "LN":"Guansing", "Grade":"1.00"},
# ]

obj = open(file_path, 'r')
print(obj)
for line in obj:
  print(line)


# stnds_dict = json.load(obj)
obj.close()
# print(stnds_dict)


print("\tLastName\t\tGrade")
for stud in student_dict:
  print("\t{}""\t".format(stud["LN"]), stud["Grade"])

"""
Program: doctor.py
Author: Ken
Conducts an interactive session of nondirective psychotherapy.
"""

import random

hedges = ("Please tell me more.",
          "Many of my patients tell me the same thing.",
          "Please coninue.")

qualifiers = ("Why do you say that ",
              "You seem to think that ",
              "Can you explain why ")

replacements = {"I":"you", "me":"you", "my":"your",
                "we":"you", "us":"you", "mine":"yours", "You":"I", "are":"am"}

def reply(sentence):
    """Implements two different reply strategies."""
    probability = random.randint(1, 4)
    if probability == 1:
        return random.choice(hedges)
    else:
        return random.choice(qualifiers) + changePerson(sentence)

def changePerson(sentence):
    """Replaces first person pronouns with second person
    pronouns."""
    words = sentence.split()
    replyWords = []
    for word in words:
        replyWords.append(replacements.get(word, word))
    return " ".join(replyWords)

def main():
    """Handles the interaction between patient and doctor."""
    print("Good morning, I hope you are well today.")
    print("What can I do for you?")
    while True:
        sentence = input("\n>> ")
        if sentence.upper() == "QUIT":
            print("Have a nice day!")
            break
        print(reply(sentence))

# The entry point for program execution
if __name__ == "__main__":
    main()